### ISSUE TITLE
ModuleCoPFollowTransform could use prefabs better

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityPartModules#2]
https://github.com/KSPModdingLibs/KSPCommunityPartModules/blob/31ba0f652ae7ec97ad7711aa50044bd375f966c9/Source/Modules/ModuleCoPFollowTransform.cs#L23

If you actually let this happen during loading, then the transform reference will be baked into the part prefab and copied correctly when the prefab is cloned.  That's generally better than looking up the transform every time the part is loaded (loading a save, etc).

The transform reference itself would need to be public or have [SerializeField] on it.

Another thing to look out for - B9PS may call OnLoad during flight with a different transform.

You can also completely disable the module in cases where the transform isn't found by setting `isEnabled` and `enabled` to false, though maybe that case should be pretty rare.

**Comment by SofieBrink** [comment]
Thanks, that's a great point. i wasn't fully aware (anymore) that things could get built into the prefab like that. will change it.
